### ISSUE TITLE
vijand aanmaken

### ISSUE THREAD

**Issue by lisannee** [informatica-emmauscollege/1920-4V-LEERLING-GAME-frederique-en-lisanne#5]
# Vijand

- [x] vijand wordt getekend

- [x] vijand beweegt uit zichzelf

- [x] vijand kan speler raken, en dan gaat de speler af

**Comment by lisannee** [comment]
-[x] vijand wordt getekend 
-[x] vijand beweegt uit zichzelf link en rechts
-[x] vijand kan speler raken en de speler verliest als de vijand hem aanraakt

**Comment by lisannee** [comment]
- [ ] vijand wordt getekend

- [ ] vijand beweegt uit zichzelf

- [ ] vijand kan speler raken, en dan gaat de speler af

**Comment by FrederiqueK** [comment]
Alles staat nu bovenaan bij elkaar. :)

**Comment by lisannee** [comment]
het is klaar
